const assets='../assets/img/';
const imageMap={'foto-obra-altiplano.jpg':'foto-obra-altiplano-839.webp','foto-equipo-yungay.jpg':'foto-equipo-yungay-1024.webp','foto-obra-san-juan-de-dios.jpg':'foto-obra-san-juan-de-dios-1200.webp','foto-obra-mega-penal-ica.jpg':'foto-obra-mega-penal-ica-1024.webp','foto-obra-matucana.jpg':'foto-obra-matucana-1024.webp','foto-obra-drat-tacna.jpg':'foto-obra-drat-tacna-1024.webp','cli-china-railway.png':'cli-china-railway-100.webp','cli-seal-telecom.png':'cli-seal-telecom-86.webp','cli-convergint.png':'cli-convergint-168.webp','cli-calaminon.png':'cli-calaminon-290.webp','cli-dominion.png':'cli-dominion-135.webp','cli-interamsa.png':'cli-interamsa-477.webp','cli-region-tacna.png':'cli-region-tacna-79.webp'};
const escapeHtml=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.getElementById('client-logos').innerHTML=BTS.clientes.map(c=>`<img src="${assets+imageMap[c.img]}" alt="${escapeHtml(c.nombre)}" loading="lazy">`).join('');
document.getElementById('solutions-list').innerHTML=BTS.lineas.map((l,i)=>`<details${i===0?' open':''}><summary><small>0${i+1}</small>${escapeHtml(l.nombre)}</summary><p>${escapeHtml(l.resumen)}</p><ul>${l.items.map((s,j)=>`<li><button data-line="${i}" data-item="${j}">${escapeHtml(s.nombre)}<span class="detail-action">Ver detalle</span></button></li>`).join('')}</ul></details>`).join('');
document.getElementById('project-grid').innerHTML=BTS.obras.map(o=>`<article class="project-card"><div class="photo"><img src="${assets+imageMap[o.img]}" alt="${escapeHtml(o.alt)}" loading="lazy"></div><div class="meta"><span>${escapeHtml(o.sector)}</span><span>${escapeHtml(o.lugar)}</span></div><h3>${escapeHtml(o.nombre)}</h3><p>${escapeHtml(o.trabajo)}</p></article>`).join('');
document.getElementById('steps').innerHTML=BTS.pasos.map((p,i)=>`<article class="step"><span>0${i+1} /</span><h3>${escapeHtml(p.titulo)}</h3><p>${escapeHtml(p.detalle)}</p></article>`).join('');
const dialog=document.getElementById('solution-dialog');let lastButton;
document.getElementById('solutions-list').addEventListener('click',e=>{const b=e.target.closest('button[data-item]');if(!b)return;const l=BTS.lineas[b.dataset.line],s=l.items[b.dataset.item];lastButton=b;document.getElementById('dialog-area').textContent=l.nombre;document.getElementById('dialog-title').textContent=s.nombre;document.getElementById('dialog-description').textContent=s.lead||s.detalle;document.getElementById('dialog-scope').innerHTML=(s.alcance||[]).map(a=>`<span>${escapeHtml(a)}</span>`).join('');document.getElementById('dialog-cta').href='https://wa.me/51938429611?text='+encodeURIComponent('Hola BTS, quisiera información sobre '+s.nombre+'.');dialog.setAttribute('aria-labelledby','dialog-title');dialog.showModal()});
dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>lastButton?.focus());

